---

- name: dependencies
  package:
    name: "{{ packages }}"
  vars:
    packages:
      - sc3-plugins
      - supercollider
  become: true
  tags: admin

- name: package
  pip:
    name: FoxDot
    executable: pip3
    extra_args: --user
  tags: user
