---

- hosts: localhost

  pre_tasks:

  - name: ensure ~/bin
    file:
      name: ~/bin
      state: directory
    tags: user

  - name: ensure pip3
    package:
      name: python3-pip
    become: true
    tags: admin

  roles:
    - {role: arcade, tags: ['arcade', 'game']}
    - {role: foxdot, tags: ['foxdot', 'sound']}
    - {role: manim, tags: ['manim', 'image']}
    - {role: pyxel, tags: ['pyxel', 'game']}
    - {role: renpy, tags: ['renpy', 'text']}
    - {role: speech, tags: ['speech', 'sound']}
