---

- name: dependencies
  package:
    name: "{{ packages }}"
  vars:
    packages:
      - libsdl2-dev
      - libsdl2-image-dev
  become: true
  tags: admin

- name: package
  pip:
    name: pyxel
    executable: pip3
    extra_args: --user
  tags: user
